### ISSUE TITLE
can't get this to work with vim-plug

### ISSUE THREAD

**Issue by aareman** [AlphaTechnolog/pywal.nvim#1]
Trying out this plugin, but getting a syntax error "variable as is not defined"

using vim-plug

**Comment by AlphaTechnolog** [comment]
Hi! Sorry for the late respond. I think it's a problem in the README.md

Try with this:

```
Plug 'AlphaTechnolog/pywal.nvim', { 'as': 'pywal' }
```

**Comment by AlphaTechnolog** [comment]
In the README.md I put a code like this, I think it not works:

```vim
Plug 'AlphaTechnolog/pywal.nvim', as = 'pywal'
```

**Comment by AlphaTechnolog** [comment]
![Screenshot from 2022-01-20 17-34-18](https://user-images.githubusercontent.com/54639968/150425818-3cf2f9b6-e9b3-4a92-af48-a983f8685f1d.png)
> It works for me
In your case you can activate it with `colorscheme pywal`

**Comment by AlphaTechnolog** [comment]
This works for me, closing... If you want to reopen it because you have any problem, let me know it

> NOTE: Updating README.md for correct instructions...
