### ISSUE TITLE
colorscheme pywal not found! ERROR

### ISSUE THREAD

**Issue by XXCryp70XX** [AlphaTechnolog/pywal.nvim#10]
EDIT: I just fixed the error i just had to put `use { 'AlphaTechnolog/pywal.nvim', as = 'pywal' }` in plugins.lua

Hello im new to nvim so please dont judge me, anyways i was trying to install pywal but i failed with this error:
Error detected while processing /home/khaled/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/khaled/.config/nvim/lua/user/pywal/init.lua:2: module 'pywal.core' not f
ound:
        no field package.preload['pywal.core']
        no file './pywal/core.lua'
        no file '/home/khaled/.config/nvim/neovim/.deps/usr/share/luajit-2.1.0-beta3/pywal/core.lua'
        no file '/usr/local/share/lua/5.1/pywal/core.lua'
        no file '/usr/local/share/lua/5.1/pywal/core/init.lua'
        no file '/home/khaled/.config/nvim/neovim/.deps/usr/share/lua/5.1/pywal/core.lua'
        no file '/home/khaled/.config/nvim/neovim/.deps/usr/share/lua/5.1/pywal/core/init.lua'
        no file './pywal/core.so'
        no file '/usr/local/lib/lua/5.1/pywal/core.so'
        no file '/home/khaled/.config/nvim/neovim/.deps/usr/lib/lua/5.1/pywal/core.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './pywal.so'
        no file '/usr/local/lib/lua/5.1/pywal.so'
        no file '/home/khaled/.config/nvim/neovim/.deps/usr/lib/lua/5.1/pywal.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /home/khaled/.config/nvim/lua/user/pywal/init.lua:2: in main chunk
        [C]: in function 'require'
        /home/khaled/.config/nvim/init.lua:7: in main chunk

**Comment by AlphaTechnolog** [comment]
Which version of neovim are you using? And what vim package manager are you using? And what's your os?

**Comment by AlphaTechnolog** [comment]
Ah this is fixed lol, well closing
