### ISSUE TITLE
Highlight color of vim illuminate is same as the text color

### ISSUE THREAD

**Issue by PhosCity** [AlphaTechnolog/pywal.nvim#11]
https://github.com/RRethy/vim-illuminate

The highlight color of vim illuminate is same color as the text causing it to be unreadable. Is there something that can be done to solve this?

**Comment by mbpowers** [comment]
Not sure if this is the proper way, but I go into `~/.local/share/nvim/site/pack/packer/start/pywal/lua/pywal/config.lua` (might be somewhere else depending on package manager/lazy loading) and change/add values in the table. 
For example I have, 
```lua
M.highlights_base = function (colors)
  return {
    -- other highlights ...

    illuminatedWord = { guifg = colors.color6 },
    illuminatedCurWord = { guifg = colors.color6 },

    -- more highlights ...
  }
end
```

`colors.color0` through `colors.color15` should be your pywal colors.

**Comment by PhosCity** [comment]
Awesome, thanks! That does solve my problem.
