### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by vaskark** [AlphaTechnolog/pywal.nvim#13]
```
vim.highlight.create is deprecated, use vim.api.nvim_set_hl instead. See :h deprecated                     
This function will be removed in Nvim version 0.9                                                          
stack traceback:                                                                                           
        /usr/share/nvim/runtime/lua/vim/highlight.lua:14: in function 'hi'                                 
        ...im/site/pack/packer/start/pywal/lua/pywal/highlights.lua:8: in function 'highlight_all'         
        ...are/nvim/site/pack/packer/start/pywal/lua/pywal/init.lua:8: in function 'setup'                 
        [string ":lua"]:1: in main chunk                                                                   
        [C]: in function 'cmd'                                                                             
        /home/vaskark/.config/nvim/init.lua:7: in main chunk 
```

My line 7 is:

`vim.cmd [[colorscheme pywal]]`

I've also set lualine theme to `pywal-nvim`. But when pywal loads a new theme the colors do not change unless I reload the file in place.

I'm using neovim (git updates ppa) on Ubuntu 22.04.1.
Thanks.

Edit: my nvim [config](https://github.com/vaskark/nvim)

Edit (again): I went back to the stable release ppa channel and the problem has disappeared. It still doesn't reload automatically when a new pywal theme is loaded, however.

**Comment by AlphaTechnolog** [comment]
This should be solved by #14 

> This issue is originated because vim.highlight.create was deprecated.
