### ISSUE TITLE
Commented lines and highlight color when pressing 'V' are the same

### ISSUE THREAD

**Issue by zakissimo** [AlphaTechnolog/pywal.nvim#3]
Thanks for the previous issue ;)

I noticed something else. As you can see below, the highlight color when selecting a line is the same of commented line of text rendering it invisible.

![2022-02-08-175538_532x154_scrot](https://user-images.githubusercontent.com/64891486/153036499-87b25270-f264-4050-9651-7ae8d477e1b2.png)

Also, I don't think the following deserves new issues open so I'll ask here: 
-Is there a way to color NvimTree background differently?
-Not remove the frame around Telescope?

Thanks again

**Comment by AlphaTechnolog** [comment]
Oh sure, Thank you for use pywal.nvim :D

You are using treesitter? Or are using the native neovim syntax highlighting?

**Comment by AlphaTechnolog** [comment]
Unfortunatelly for now no, but I am working in some options to modify more the aspect of the theme :D

**Comment by AlphaTechnolog** [comment]
The same with Telescope, I will checkout it highlights and some options to modify the aspect of it :)

**Comment by zakissimo** [comment]
> Oh sure, Thank you for use pywal.nvim :D
> 
> You are using treesitter? Or are using the native neovim syntax highlighting?

Yes I'm using treesitter.
Thanks for the feedback I'll try to tweak the config.lua if I find the courage.

**Comment by AlphaTechnolog** [comment]
Thank you for the collaboration, I push a commit that solve this problem in main :D update the plugin :)

**Comment by AlphaTechnolog** [comment]
I push another commit that solves the problem with the Telescope border in main branch, update the plugin :D

![telescope](https://user-images.githubusercontent.com/54639968/153522251-4d755e15-9943-4e83-a36f-8ad410015084.png)

**Comment by AlphaTechnolog** [comment]
Closing because the problems are solved for me, if you have any problem, please let me know it (reopen the issue)
