### ISSUE TITLE
 Indent lines blend in with the background rendering them invisible

### ISSUE THREAD

**Issue by zakissimo** [AlphaTechnolog/pywal.nvim#4]
Pywal:
![2022-02-08-181101_632x358_scrot](https://user-images.githubusercontent.com/64891486/153039567-c57cbab6-2b39-43ba-92e3-e122f94164b8.png)

Catppuccin theme:
![2022-02-08-180954_704x499_scrot](https://user-images.githubusercontent.com/64891486/153039533-8ed74c8f-69b7-4c30-a7ef-2200a671b400.png)

Edit: Same thing with the line numbers too

**Comment by AlphaTechnolog** [comment]
It seems like with a problem with the highlights of pywal.nvim, I will checkout it :D Thank you for using pywal.nvim :3

**Comment by zakissimo** [comment]
Thanks for being active on this project ! 

Yes it's the one I'm using, but I can use another one if it makes it easier.

**Comment by AlphaTechnolog** [comment]
I fix this problem with indent-blankline integration

![demonstration](https://user-images.githubusercontent.com/54639968/153291631-71ff4a04-11f6-4b86-9653-c5345d1ac7ea.png)

Changes in the main branch, update the plugin :3

> Closing this issue because the problem is fixed for me, if you have any problem reopen this, thank you a lot :D
