### ISSUE TITLE
Whitespaces (listchars) have the same color of backgroung

### ISSUE THREAD

**Issue by MarcoRiggirello** [AlphaTechnolog/pywal.nvim#5]
Using pywal.nvim colorscheme when `vim.opt.list=true` is set all listchars of Whitespace highlightning group are invisible. Here's an example:
![immagine](https://user-images.githubusercontent.com/83573323/154804202-546c9771-7dea-491d-bb3d-706d4ad07b9c.png)
![immagine](https://user-images.githubusercontent.com/83573323/154804293-a2d86997-19cc-4d6b-b820-94e0de488801.png)

Seems like a problem in pywal colorscheme config, where for Whitespace `guifg=colors.background`. If I set another color, for example `color1` (since other lischars, like eol, use NonText highlightning - see `:help listchars`)  the problem is solved:
![immagine](https://user-images.githubusercontent.com/83573323/154805250-76f7e6a8-5ff7-4814-899b-4c0be73118ae.png)

I use wezterm as terminal emulator and nvim v0.6.1 on Arch Linux.

**Comment by AlphaTechnolog** [comment]
Oh sure, It seems like a problem with the highlights in the plugin, I Will check this later, sorry...

The solution for now is add manually the highlight for NonText. Later I will push a fix for this

Thank you a lot for use pywal.nvim :)

**Comment by MarcoRiggirello** [comment]
Thank you for your work! Just a question: how can I add manually the highlight?

**Comment by AlphaTechnolog** [comment]
Oh sure you can add it with this lua code:

```lua
local hi = vim.highlight.create
local colors = require('pywal.core').get_colors()

hi('Whitespace', { guifg = colors.color1 }, false)
```

> The correct highlight isn't NonText it's Whitespace, sorry xd

**Comment by MarcoRiggirello** [comment]
Thank you!

**Comment by AlphaTechnolog** [comment]
Pushed changes to main branch, remove the custom highlight and update the plugin ;D

Thanks a lot for use pywal.nvim, enjoy using it!
